services:
  tg-ws-proxy:
    image: lordarrin/tg-ws-proxy:latest
    container_name: tg-ws-proxy
    restart: unless-stopped
    network_mode: host
    environment:
      - PROXY_PORT=1443
      - PROXY_SECRET=
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=64m
      - /home/app/.cache:noexec,nosuid,size=32m
    deploy:
      resources:
        limits:
          memory: 384M
          cpus: '1'
  
  web-interface:
    container_name: web-interface
    restart: unless-stopped
    network_mode: host 
    user: "root"
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
